[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "playground"
version = "0.1.0"
dependencies = [
    "Flask==3.1.0",
    "Flask-SQLAlchemy==3.1.1",
    "click==8.1.8",
    "psycopg2-binary==2.9.10",
    "Flask-Migrate==4.1.0"
]

